// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/codeofmario/wiremap/internal/wiremap/config"
	"github.com/codeofmario/wiremap/internal/wiremap/docker"
	"github.com/codeofmario/wiremap/internal/wiremap/handler"
	"github.com/codeofmario/wiremap/internal/wiremap/router"
	"github.com/codeofmario/wiremap/internal/wiremap/service"
	"github.com/codeofmario/wiremap/internal/wiremap/ws"
)

// Injectors from wire.go:

func InitializeApp(port2 int, devMode2 bool, configFile2 string, hosts2 []string) (*App, error) {
	settings := config.NewSettings(port2, devMode2, configFile2, hosts2)
	clientPool, err := docker.NewClientPool(settings)
	if err != nil {
		return nil, err
	}
	containerService := service.NewContainerService(clientPool)
	containerHandler := handler.NewContainerHandler(containerService)
	networkService := service.NewNetworkService(clientPool)
	networkHandler := handler.NewNetworkHandler(networkService)
	filesystemService := service.NewFilesystemService(clientPool)
	filesystemHandler := handler.NewFilesystemHandler(filesystemService)
	hub := ws.NewHub(containerService, settings)
	engine := router.InitRoutes(settings, clientPool, containerHandler, networkHandler, filesystemHandler, hub)
	app := NewApp(engine, settings)
	return app, nil
}
